# Generated by Django 5.1 on 2024-08-20 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
